import { Libre_Franklin } from "next/font/google";
import Header from "./components/Header";
import "./globals.css";
import Footer from "./components/Footer";

const libreFranklin = Libre_Franklin({ subsets: ["latin"] });

export const metadata = {
  title: "Ivan Palacios - Frontend Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={libreFranklin.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
